version: '3.7'
services:

  random_generator:
    build:
      context: ./random_generator
      dockerfile: ./Dockerfile
    image: random_generator_image:latest
    ports:
      - "80:80"
    networks:
      - training_network
  number_consumer:
    build:
      context: ./number_consumer
      dockerfile: ./Dockerfile
    image: number_consumer_image:latest
    volumes:
      - ./data_from_number_consumer:/data_from_number_consumer
    networks:
      - training_network
  data_from_file:
    build:
      context: ./data_from_file
      dockerfile: ./Dockerfile
    image: data_from_file_image:latest
    ports:
      - "8080:8080"
    networks:
      - training_network
networks:
  training_network:
    driver: bridge
    name: training_network